# Generated by Django 3.2.8 on 2021-10-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('cod_territorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_territorio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('num_resolucion', models.IntegerField(primary_key=True, serialize=False)),
                ('laboratorio_vacuna', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_resolucion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_resolucion', models.DateTimeField()),
                ('anio', models.IntegerField(default=0)),
                ('nom_territorio', models.CharField(max_length=20)),
                ('laboratorio_vacuna', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('uso_vacuna', models.CharField(max_length=40)),
                ('fecha_corte', models.DateTimeField()),
                ('cod_territorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='asignacion_vacunas.territorio')),
                ('num_resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='asignacion_vacunas.vacuna')),
            ],
        ),
    ]
