# Generated by Django 3.2.8 on 2021-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('asignacion_vacunas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='nom_territorio',
        ),
        migrations.AddField(
            model_name='territorio',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='password',
            field=models.CharField(default='0', max_length=256, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='territorio',
            name='username',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='num_resolucion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='territorio',
            name='cod_territorio',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='territorio',
            name='nom_territorio',
            field=models.CharField(default='0', max_length=20, verbose_name='nom_territorio'),
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
